### ISSUE TITLE
Chapter 6, Deploying a real-time inference pipeline, Cannot find Deploy Button

### ISSUE THREAD

**Issue by michaelmiscanuk** [PacktPublishing/Microsoft-Certified-Azure-Data-Scientist-Associate-Certification-Guide#1]
Hi,

In Chapter 6: Deploying a real-time inference pipeline.

I don't see the deploy button in the pipeline.
I see only publish, but it will publish the pipeline. 
![image](https://user-images.githubusercontent.com/37830487/207888678-aee13317-ac7f-4b24-bd6f-7cc72ca7c17d.png)

And In this published pipeline I also cannot see the deploy button.
![image](https://user-images.githubusercontent.com/37830487/207889789-b4a2b352-bd42-475f-9391-f94c54aae83e.png)

 Is here some new process to Set up real-time endpoint?
 Thank you.

**Comment by andreasbotsikas** [comment]
Hi @michaelmiscanuk, thanks for reaching out and best wishes for a happy new year!

Indeed the platform is [evolving into v2](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-migrate-from-v1) which aims to unify the capabilities and the processes from all experiences (UI and code). As you may have noticed, the designer has evolved to allow developers to [register their own components](https://learn.microsoft.com/en-us/azure/machine-learning/concept-component), which enables great scenarios like a data scientist [coding and registering components](https://github.com/rndazurescript/FunWithAzureML/tree/master/cli-v2-r-forecasting) to be reused by business analysts in different datasets etc.

Regarding your question, indeed the deployment of the endpoints has moved to the pipeline job. You can see how to publish a job as a real time endpoint in the [ms learn article](https://learn.microsoft.com/en-us/azure/machine-learning/tutorial-designer-automobile-price-deploy). Here is how it looks on my side:
![image](https://user-images.githubusercontent.com/1227433/210136600-2abf66ea-e86e-46a6-a833-656e87ff73a9.png)
You can modify the real time endpoint pipeline as you wish (e.g. the SQL transformation mentioned in the book):
![image](https://user-images.githubusercontent.com/1227433/210782234-51c3488d-bada-4784-a279-398328e6864d.png)
Once submitted, you go to the job that completed and you select the `Deploy` option:
![image](https://user-images.githubusercontent.com/1227433/210782939-ee69e7bd-fa19-45f7-a937-4e572ffdf7ed.png)
You can then access the endpoint in the endpoints section as described in the book:
![image](https://user-images.githubusercontent.com/1227433/210812043-de96b32b-17ae-42a8-ad9e-cd98cadbddfa.png)

Let us know if you need any help publishing your real time endpoint or let us know if you are covered to close this issue.

Happy new year!

**Comment by andreasbotsikas** [comment]
Closing this issue as we feel that we have provided the necessary information regarding the new way of publishing Real Time endpoints. Keep in mind that this is not relevant information for the DP 100 certification so you shouldn't worry about such minor UI differentiations. Azure ML is a strong growing cloud service, and it constantly gets improved, based on the customer feedback.
